# Generated by Django 4.2.4 on 2023-11-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0007_product_img2_alter_product_img_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Dresses', 'Dresses')], default='Shirt', max_length=30),
        ),
    ]
