# Generated by Django 4.2.4 on 2023-11-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0008_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
