# Generated by Django 4.2.4 on 2023-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0011_add_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='adress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
