# Generated by Django 5.0.2 on 2024-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0013_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='add_cart',
        ),
        migrations.DeleteModel(
            name='main_category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
