# Generated by Django 5.0.2 on 2024-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0014_remove_product_main_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
