# Generated by Django 5.0.2 on 2024-03-31 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0017_brand_categories_color_filter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/images')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=100)),
                ('information', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=200)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200)),
                ('created_date', models.CharField(default=django.utils.timezone.now, max_length=300)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp5.categories')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp5.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp5.color')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp5.filter_price')),
            ],
        ),
    ]
