# Generated by Django 5.0.2 on 2024-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0020_images_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
