# Generated by Django 5.0.2 on 2024-04-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0021_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kid', 'Kid'), ('Beauty', 'Beauty')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
