# Generated by Django 5.0.2 on 2024-04-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0024_alter_filter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Beauty', 'Beauty')], max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Categories',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp5.sub_category'),
        ),
    ]
