# Generated by Django 5.0.2 on 2024-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0025_sub_category_rename_categories_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Beauty', 'Beauty')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
    ]
