# Generated by Django 5.0.2 on 2024-04-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0026_alter_product_sub_category_delete_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
