# Generated by Django 5.0.2 on 2024-04-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0027_remove_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='Categories',
        ),
    ]
