# Generated by Django 5.0.2 on 2024-04-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0028_rename_categories_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categories',
            new_name='categories',
        ),
    ]
