# Generated by Django 5.0.2 on 2024-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0032_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
