# Generated by Django 5.0.2 on 2024-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0033_remove_contact_subject_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
