# Generated by Django 5.0.2 on 2024-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0035_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
