# Generated by Django 5.0.2 on 2024-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0038_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=1, upload_to='img/images'),
            preserve_default=False,
        ),
    ]
