# Generated by Django 5.0.2 on 2024-04-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0040_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='subject',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='email',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='messagereview',
        ),
    ]
