# Generated by Django 5.0.2 on 2024-04-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0041_rename_subject_review_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='messagereview',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='subject',
        ),
    ]
