# Generated by Django 5.0.2 on 2024-05-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0042_rename_gmail_review_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='subject',
            new_name='review',
        ),
    ]
